#include "ck/hotkeys.hpp"

#include "ck/commands/ck_chat.hpp"
#include "ck/commands/ck_config.hpp"
#include "ck/commands/ck_du.hpp"
#include "ck/commands/ck_edit.hpp"
#include "ck/commands/ck_find.hpp"
#include "ck/commands/ck_utilities.hpp"
#include "ck/commands/common.hpp"
#include "ck/commands/json_view.hpp"

#include <tvision/views.h>
#include <tvision/tkeys.h>
#include <tvision/editors.h>

namespace ck::hotkeys
{

namespace
{

const CommandLabel kDefaultLabels[] = {
    {cmQuit, "", "Quit"},
    {cmClose, "", "Close"},
    {cmMenu, "", "Menu"},
    {cmZoom, "", "Zoom"},
    {cmResize, "", "Resize/Move"},
    {cmNext, "", "Next Window"},
    {cmTile, "", "Tile"},
    {cmCascade, "", "Cascade"},
    {cmOpen, "", "Open"},
    {cmNew, "", "New"},
    {cmChangeDir, "", "Change Directory"},
    {cmSave, "", "Save"},
    {cmSaveAs, "", "Save As"},
    {cmCopy, "", "Copy"},
    {cmCut, "", "Cut"},
    {cmPaste, "", "Paste"},
    {cmUndo, "", "Undo"},
    {cmFind, "", "Find"},
    {cmReplace, "", "Replace"},
    {cmSearchAgain, "", "Find Next"},
    {cmHelp, "", "Help"},

    {commands::common::ReturnToLauncher, "", "Return"},
    {commands::common::About, "", "About"},

    {commands::utilities::LaunchTool, "ck-utilities", "Launch"},
    {commands::utilities::ToggleEventViewer, "ck-utilities", "Event Viewer"},
    {commands::utilities::NewLauncher, "ck-utilities", "New Launcher"},
    {commands::utilities::ShowCalendar, "ck-utilities", "Calendar"},
    {commands::utilities::ShowAsciiTable, "ck-utilities", "ASCII Table"},
    {commands::utilities::ShowCalculator, "ck-utilities", "Calculator"},

    {commands::disk_usage::ViewFiles, "ck-du", "Files"},
    {commands::disk_usage::ViewFilesRecursive, "ck-du", "Files (Recursive)"},
    {commands::disk_usage::ViewFileTypes, "ck-du", "Types"},
    {commands::disk_usage::ViewFileTypesRecursive, "ck-du", "Types (Subdirs)"},
    {commands::disk_usage::SortUnsorted, "ck-du", "Sort Unsorted"},
    {commands::disk_usage::SortNameAsc, "ck-du", "Sort By Name"},
    {commands::disk_usage::SortNameDesc, "ck-du", "Sort By Name (Desc)"},
    {commands::disk_usage::SortSizeDesc, "ck-du", "Sort By Size"},
    {commands::disk_usage::SortSizeAsc, "ck-du", "Sort By Size (Asc)"},
    {commands::disk_usage::SortModifiedDesc, "ck-du", "Sort By Modified"},
    {commands::disk_usage::SortModifiedAsc, "ck-du", "Sort By Modified (Asc)"},
    {commands::disk_usage::OptionFollowNever, "ck-du", "Do Not Follow Links"},
    {commands::disk_usage::OptionFollowCommandLine, "ck-du", "Follow CLI Links"},
    {commands::disk_usage::OptionFollowAll, "ck-du", "Follow All Links"},
    {commands::disk_usage::OptionToggleHardLinks, "ck-du", "Toggle Hard Links"},
    {commands::disk_usage::OptionToggleNodump, "ck-du", "Toggle Nodump"},
    {commands::disk_usage::OptionToggleErrors, "ck-du", "Toggle Errors"},
    {commands::disk_usage::OptionToggleOneFs, "ck-du", "Stay On One FS"},
    {commands::disk_usage::OptionEditIgnores, "ck-du", "Edit Ignore Patterns"},
    {commands::disk_usage::OptionEditThreshold, "ck-du", "Edit Threshold"},
    {commands::disk_usage::OptionLoad, "ck-du", "Load Options"},
    {commands::disk_usage::OptionSave, "ck-du", "Save Options"},
    {commands::disk_usage::OptionSaveDefaults, "ck-du", "Save Defaults"},

    {commands::config::ReloadApps, "ck-config", "Reload"},
    {commands::config::EditApp, "ck-config", "Edit Options"},
    {commands::config::ResetApp, "ck-config", "Reset"},
    {commands::config::ClearApp, "ck-config", "Clear Defaults"},
    {commands::config::ExportApp, "ck-config", "Export"},
    {commands::config::ImportApp, "ck-config", "Import"},
    {commands::config::OpenConfigDir, "ck-config", "Open Config Dir"},

    {commands::find::NewSearch, "ck-find", "New Search"},
    {commands::find::LoadSpec, "ck-find", "Load Spec"},
    {commands::find::SaveSpec, "ck-find", "Save Spec"},
    {commands::find::BrowseStart, "ck-find", "Browse"},
    {commands::find::TextOptions, "ck-find", "Text Options"},
    {commands::find::NamePathOptions, "ck-find", "Name/Path Options"},
    {commands::find::TimeFilters, "ck-find", "Time Filters"},
    {commands::find::SizeFilters, "ck-find", "Size Filters"},
    {commands::find::TypeFilters, "ck-find", "Type Filters"},
    {commands::find::PermissionOwnership, "ck-find", "Permissions"},
    {commands::find::TraversalFilters, "ck-find", "Traversal"},
    {commands::find::ActionOptions, "ck-find", "Actions"},
    {commands::find::DialogLoadSpec, "ck-find", "Load Spec"},
    {commands::find::DialogSaveSpec, "ck-find", "Save Spec"},

    {commands::json_view::Find, "ck-json-view", "Find"},
    {commands::json_view::FindNext, "ck-json-view", "Find Next"},
    {commands::json_view::FindPrev, "ck-json-view", "Find Previous"},
    {commands::json_view::EndSearch, "ck-json-view", "End Search"},
    {commands::json_view::Level0, "ck-json-view", "Level 0"},
    {commands::json_view::Level1, "ck-json-view", "Level 1"},
    {commands::json_view::Level2, "ck-json-view", "Level 2"},
    {commands::json_view::Level3, "ck-json-view", "Level 3"},
    {commands::json_view::Level4, "ck-json-view", "Level 4"},
    {commands::json_view::Level5, "ck-json-view", "Level 5"},
    {commands::json_view::Level6, "ck-json-view", "Level 6"},
    {commands::json_view::Level7, "ck-json-view", "Level 7"},
    {commands::json_view::Level8, "ck-json-view", "Level 8"},
    {commands::json_view::Level9, "ck-json-view", "Level 9"},

    {commands::chat::NewChat, "ck-chat", "New Chat"},
    {commands::chat::ManageModels, "ck-chat", "Manage Models"},
    {commands::chat::ManagePrompts, "ck-chat", "Manage Prompts"},
    {commands::chat::SendPrompt, "ck-chat", "Send"},
    {commands::chat::ShowThinking, "ck-chat", "Show Thinking"},
    {commands::chat::HideThinking, "ck-chat", "Hide Thinking"},
    {commands::chat::ShowAnalysis, "ck-chat", "Show Analysis"},
    {commands::chat::HideAnalysis, "ck-chat", "Hide Analysis"},
    {commands::chat::CopyLastResponse, "ck-chat", "Copy Last Response"},

    {commands::edit::cmToggleWrap, "ck-edit", "Toggle Wrap"},
    {commands::edit::cmToggleMarkdownMode, "ck-edit", "Toggle Markdown"},
    {commands::edit::cmHeading1, "ck-edit", "Heading 1"},
    {commands::edit::cmHeading2, "ck-edit", "Heading 2"},
    {commands::edit::cmHeading3, "ck-edit", "Heading 3"},
    {commands::edit::cmHeading4, "ck-edit", "Heading 4"},
    {commands::edit::cmHeading5, "ck-edit", "Heading 5"},
    {commands::edit::cmHeading6, "ck-edit", "Heading 6"},
    {commands::edit::cmClearHeading, "ck-edit", "Clear Heading"},
    {commands::edit::cmMakeParagraph, "ck-edit", "Paragraph"},
    {commands::edit::cmInsertLineBreak, "ck-edit", "Line Break"},
    {commands::edit::cmBold, "ck-edit", "Bold"},
    {commands::edit::cmItalic, "ck-edit", "Italic"},
    {commands::edit::cmBoldItalic, "ck-edit", "Bold + Italic"},
    {commands::edit::cmStrikethrough, "ck-edit", "Strikethrough"},
    {commands::edit::cmInlineCode, "ck-edit", "Inline Code"},
    {commands::edit::cmCodeBlock, "ck-edit", "Code Block"},
    {commands::edit::cmRemoveFormatting, "ck-edit", "Clear Formatting"},
    {commands::edit::cmToggleBlockQuote, "ck-edit", "Block Quote"},
    {commands::edit::cmToggleBulletList, "ck-edit", "Bullet List"},
    {commands::edit::cmToggleNumberedList, "ck-edit", "Numbered List"},
    {commands::edit::cmConvertTaskList, "ck-edit", "Task List"},
    {commands::edit::cmToggleTaskCheckbox, "ck-edit", "Toggle Checkbox"},
    {commands::edit::cmIncreaseIndent, "ck-edit", "Increase Indent"},
    {commands::edit::cmDecreaseIndent, "ck-edit", "Decrease Indent"},
    {commands::edit::cmDefinitionList, "ck-edit", "Definition List"},
    {commands::edit::cmToggleSmartList, "ck-edit", "Auto List"},
    {commands::edit::cmInsertLink, "ck-edit", "Insert Link"},
    {commands::edit::cmInsertReferenceLink, "ck-edit", "Insert Reference"},
    {commands::edit::cmAutoLinkSelection, "ck-edit", "Auto Link"},
    {commands::edit::cmInsertImage, "ck-edit", "Insert Image"},
    {commands::edit::cmInsertFootnote, "ck-edit", "Insert Footnote"},
    {commands::edit::cmInsertHorizontalRule, "ck-edit", "Insert Rule"},
    {commands::edit::cmEscapeSelection, "ck-edit", "Escape Selection"},
    {commands::edit::cmInsertTable, "ck-edit", "Insert Table"},
    {commands::edit::cmTableInsertRowAbove, "ck-edit", "Row Above"},
    {commands::edit::cmTableInsertRowBelow, "ck-edit", "Row Below"},
    {commands::edit::cmTableDeleteRow, "ck-edit", "Delete Row"},
    {commands::edit::cmTableInsertColumnBefore, "ck-edit", "Column Before"},
    {commands::edit::cmTableInsertColumnAfter, "ck-edit", "Column After"},
    {commands::edit::cmTableDeleteColumn, "ck-edit", "Delete Column"},
    {commands::edit::cmTableDeleteTable, "ck-edit", "Delete Table"},
    {commands::edit::cmTableAlignDefault, "ck-edit", "Align Default"},
    {commands::edit::cmTableAlignLeft, "ck-edit", "Align Left"},
    {commands::edit::cmTableAlignCenter, "ck-edit", "Align Center"},
    {commands::edit::cmTableAlignRight, "ck-edit", "Align Right"},
    {commands::edit::cmTableAlignNumber, "ck-edit", "Align Number"},
    {commands::edit::cmReflowParagraphs, "ck-edit", "Reflow"},
    {commands::edit::cmFormatDocument, "ck-edit", "Format Document"},
};

const KeyBinding kLinuxBindings[] = {
    {cmQuit, TKey(kbAltX), "Alt-X"},
    {cmClose, TKey(kbAltF3), "Alt-F3"},
    {cmMenu, TKey(kbF10), "F10"},
    {cmZoom, TKey(kbF5), "F5"},
    {cmResize, TKey(kbCtrlF5), "Ctrl-F5"},
    {cmNext, TKey(kbF6), "F6"},
    {cmOpen, TKey(kbF2), "F2"},
    {cmCopy, TKey(kbCtrlC), "Ctrl-C"},
    {cmFind, TKey(kbCtrlF), "Ctrl-F"},
    {cmHelp, TKey(kbF1), "F1"},
    {commands::chat::CopyLastResponse, TKey('C', kbAltShift | kbShift), "Alt+Shift+C"},

    {commands::common::ReturnToLauncher, TKey(kbCtrlL), "Ctrl-L"},
    {commands::common::About, TKey(kbF1), "F1"},

    {commands::utilities::LaunchTool, TKey(kbEnter), "Enter"},
    {commands::utilities::ToggleEventViewer, TKey(kbAlt0), "Alt-0"},

    {commands::disk_usage::ViewFiles, TKey(kbF3), "F3"},
    {commands::disk_usage::ViewFilesRecursive, TKey(kbShiftF3), "Shift-F3"},
    {commands::disk_usage::ViewFileTypes, TKey(kbF4), "F4"},
    {commands::disk_usage::ViewFileTypesRecursive, TKey(kbShiftF4), "Shift-F4"},
    {commands::disk_usage::SortNameAsc, TKey(kbCtrlN), "Ctrl-N"},
    {commands::disk_usage::SortSizeDesc, TKey(kbCtrlS), "Ctrl-S"},
    {commands::disk_usage::SortModifiedDesc, TKey(kbCtrlM), "Ctrl-M"},

    {commands::config::ReloadApps, TKey(kbF5), "F5"},
    {commands::config::EditApp, TKey(kbEnter), "Enter"},

    {commands::find::NewSearch, TKey(kbF2), "F2"},
    {commands::find::LoadSpec, TKey(kbCtrlO), "Ctrl-O"},
    {commands::find::SaveSpec, TKey(kbCtrlS), "Ctrl-S"},

    {commands::json_view::Find, TKey(kbCtrlF), "Ctrl-F"},
    {commands::json_view::FindNext, TKey(kbF5), "F5"},
    {commands::json_view::FindPrev, TKey(kbShiftF5), "Shift-F5"},
    {commands::json_view::EndSearch, TKey(kbEsc), "Esc"},
    {commands::json_view::Level0, TKey(kbAlt0), "Alt-0"},
    {commands::json_view::Level1, TKey(kbAlt1), "Alt-1"},
    {commands::json_view::Level2, TKey(kbAlt2), "Alt-2"},
    {commands::json_view::Level3, TKey(kbAlt3), "Alt-3"},
    {commands::json_view::Level4, TKey(kbAlt4), "Alt-4"},
    {commands::json_view::Level5, TKey(kbAlt5), "Alt-5"},
    {commands::json_view::Level6, TKey(kbAlt6), "Alt-6"},
    {commands::json_view::Level7, TKey(kbAlt7), "Alt-7"},
    {commands::json_view::Level8, TKey(kbAlt8), "Alt-8"},
    {commands::json_view::Level9, TKey(kbAlt9), "Alt-9"},

    {commands::chat::NewChat, TKey(kbCtrlN), "Ctrl-N"},
    {commands::chat::ManageModels, TKey(kbF2), "F2"},
    {commands::chat::ManagePrompts, TKey(kbF3), "F3"},
    {commands::chat::SendPrompt, TKey(kbAltS), "Alt-S"},

    {commands::edit::cmToggleWrap, TKey(kbCtrlW), "Ctrl-W"},
    {commands::edit::cmToggleMarkdownMode, TKey(kbCtrlM), "Ctrl-M"},
    {commands::edit::cmBold, TKey(kbCtrlB), "Ctrl-B"},
    {commands::edit::cmItalic, TKey(kbCtrlI), "Ctrl-I"},
    {commands::edit::cmBoldItalic, TKey('B', kbCtrlShift | kbShift), "Ctrl+Shift+B"},
    {commands::edit::cmStrikethrough, TKey('S', kbCtrlShift | kbShift), "Ctrl+Shift+S"},
    {commands::edit::cmInlineCode, TKey(kbCtrlK), "Ctrl-K"},
    {commands::edit::cmCodeBlock, TKey('K', kbCtrlShift | kbShift), "Ctrl+Shift+K"},
    {commands::edit::cmRemoveFormatting, TKey('0', kbCtrlShift | kbShift), "Ctrl+Shift+0"},
    {commands::edit::cmMakeParagraph, TKey('P', kbCtrlShift | kbShift), "Ctrl+Shift+P"},
    {commands::edit::cmToggleBlockQuote, TKey('Q', kbCtrlShift | kbShift), "Ctrl+Shift+Q"},
    {commands::edit::cmToggleBulletList, TKey('U', kbCtrlShift | kbShift), "Ctrl+Shift+U"},
    {commands::edit::cmToggleNumberedList, TKey('O', kbCtrlShift | kbShift), "Ctrl+Shift+O"},
    {commands::edit::cmConvertTaskList, TKey('T', kbCtrlShift | kbShift), "Ctrl+Shift+T"},
    {commands::edit::cmToggleTaskCheckbox, TKey('X', kbCtrlShift | kbShift), "Ctrl+Shift+X"},
    {commands::edit::cmIncreaseIndent, TKey(kbRight, kbCtrlShift | kbShift), "Ctrl+Shift+Right"},
    {commands::edit::cmDecreaseIndent, TKey(kbLeft, kbCtrlShift | kbShift), "Ctrl+Shift+Left"},
    {commands::edit::cmDefinitionList, TKey('D', kbCtrlShift | kbShift), "Ctrl+Shift+D"},
    {commands::edit::cmToggleSmartList, TKey('A', kbCtrlShift | kbShift), "Ctrl+Shift+A"},
    {commands::edit::cmInsertLink, TKey('L', kbCtrlShift | kbShift), "Ctrl+Shift+L"},
    {commands::edit::cmInsertReferenceLink, TKey('R', kbCtrlShift | kbShift), "Ctrl+Shift+R"},
    {commands::edit::cmAutoLinkSelection, TKey('Y', kbCtrlShift | kbShift), "Ctrl+Shift+Y"},
    {commands::edit::cmInsertImage, TKey('I', kbCtrlShift | kbShift), "Ctrl+Shift+I"},
    {commands::edit::cmInsertFootnote, TKey('N', kbCtrlShift | kbShift), "Ctrl+Shift+N"},
    {commands::edit::cmInsertHorizontalRule, TKey('H', kbCtrlShift | kbShift), "Ctrl+Shift+H"},
    {commands::edit::cmEscapeSelection, TKey('E', kbCtrlShift | kbShift), "Ctrl+Shift+E"},
    {commands::edit::cmInsertTable, TKey('T', kbCtrlShift | kbAltShift), "Ctrl+Alt+T"},
    {commands::edit::cmTableInsertRowAbove, TKey(kbUp, kbCtrlShift | kbAltShift), "Ctrl+Alt+Up"},
    {commands::edit::cmTableInsertRowBelow, TKey(kbDown, kbCtrlShift | kbAltShift), "Ctrl+Alt+Down"},
    {commands::edit::cmTableDeleteRow, TKey(kbDown, kbCtrlShift | kbAltShift | kbShift), "Ctrl+Alt+Shift+Down"},
    {commands::edit::cmTableInsertColumnBefore, TKey(kbLeft, kbCtrlShift | kbAltShift), "Ctrl+Alt+Left"},
    {commands::edit::cmTableInsertColumnAfter, TKey(kbRight, kbCtrlShift | kbAltShift), "Ctrl+Alt+Right"},
    {commands::edit::cmTableDeleteColumn, TKey(kbRight, kbCtrlShift | kbAltShift | kbShift), "Ctrl+Alt+Shift+Right"},
    {commands::edit::cmTableDeleteTable, TKey('T', kbCtrlShift | kbAltShift | kbShift), "Ctrl+Alt+Shift+T"},
    {commands::edit::cmTableAlignDefault, TKey('D', kbCtrlShift | kbAltShift), "Ctrl+Alt+D"},
    {commands::edit::cmTableAlignLeft, TKey('L', kbCtrlShift | kbAltShift), "Ctrl+Alt+L"},
    {commands::edit::cmTableAlignCenter, TKey('C', kbCtrlShift | kbAltShift), "Ctrl+Alt+C"},
    {commands::edit::cmTableAlignRight, TKey('R', kbCtrlShift | kbAltShift), "Ctrl+Alt+R"},
    {commands::edit::cmTableAlignNumber, TKey('N', kbCtrlShift | kbAltShift), "Ctrl+Alt+N"},
    {commands::edit::cmReflowParagraphs, TKey('P', kbCtrlShift | kbAltShift), "Ctrl+Alt+P"},
    {commands::edit::cmFormatDocument, TKey('F', kbCtrlShift | kbAltShift), "Ctrl+Alt+F"},
    {commands::edit::cmHeading1, TKey('1', kbAltShift), "Alt-1"},
    {commands::edit::cmHeading2, TKey('2', kbAltShift), "Alt-2"},
    {commands::edit::cmHeading3, TKey('3', kbAltShift), "Alt-3"},
    {commands::edit::cmHeading4, TKey('4', kbAltShift), "Alt-4"},
    {commands::edit::cmHeading5, TKey('5', kbAltShift), "Alt-5"},
    {commands::edit::cmHeading6, TKey('6', kbAltShift), "Alt-6"},
    {commands::edit::cmClearHeading, TKey('0', kbAltShift), "Alt-0"},
    {commands::edit::cmInsertLineBreak, TKey(kbCtrlEnter), "Ctrl+Enter"},
};

const KeyBinding kMacBindings[] = {
    {cmQuit, TKey(kbCtrlQ), "Ctrl-Q"},
    {cmClose, TKey(kbCtrlW), "Ctrl-W"},
    {cmMenu, TKey(kbF10), "F10"},
    {cmZoom, TKey(kbF5), "F5"},
    {cmResize, TKey(kbCtrlF5), "Ctrl-F5"},
    {cmNext, TKey(kbF6), "F6"},
    {cmOpen, TKey(kbCtrlO), "Ctrl-O"},
    {cmCopy, TKey(kbCtrlC), "Ctrl-C"},
    {cmFind, TKey(kbCtrlF), "Ctrl-F"},
    {cmHelp, TKey(kbF1), "F1"},
    {commands::chat::CopyLastResponse, TKey('C', kbCtrlShift | kbShift), "Ctrl+Shift+C"},

    {commands::common::ReturnToLauncher, TKey(kbCtrlL), "Ctrl-L"},
    {commands::common::About, TKey(kbF1), "F1"},

    {commands::utilities::LaunchTool, TKey(kbEnter), "Enter"},
    {commands::utilities::ToggleEventViewer, TKey('0', kbCtrlShift), "Ctrl-0"},

    {commands::disk_usage::ViewFiles, TKey(kbF3), "F3"},
    {commands::disk_usage::ViewFilesRecursive, TKey(kbShiftF3), "Shift-F3"},
    {commands::disk_usage::ViewFileTypes, TKey(kbF4), "F4"},
    {commands::disk_usage::ViewFileTypesRecursive, TKey(kbShiftF4), "Shift-F4"},
    {commands::disk_usage::SortNameAsc, TKey(kbCtrlN), "Ctrl-N"},
    {commands::disk_usage::SortSizeDesc, TKey(kbCtrlS), "Ctrl-S"},
    {commands::disk_usage::SortModifiedDesc, TKey(kbCtrlM), "Ctrl-M"},

    {commands::config::ReloadApps, TKey(kbF5), "F5"},
    {commands::config::EditApp, TKey(kbEnter), "Enter"},

    {commands::find::NewSearch, TKey(kbF2), "F2"},
    {commands::find::LoadSpec, TKey(kbCtrlO), "Ctrl-O"},
    {commands::find::SaveSpec, TKey(kbCtrlS), "Ctrl-S"},

    {commands::json_view::Find, TKey(kbCtrlF), "Ctrl-F"},
    {commands::json_view::FindNext, TKey(kbF5), "F5"},
    {commands::json_view::FindPrev, TKey(kbShiftF5), "Shift-F5"},
    {commands::json_view::EndSearch, TKey(kbEsc), "Esc"},
    {commands::json_view::Level0, TKey('0', kbCtrlShift), "Ctrl-0"},
    {commands::json_view::Level1, TKey('1', kbCtrlShift), "Ctrl-1"},
    {commands::json_view::Level2, TKey('2', kbCtrlShift), "Ctrl-2"},
    {commands::json_view::Level3, TKey('3', kbCtrlShift), "Ctrl-3"},
    {commands::json_view::Level4, TKey('4', kbCtrlShift), "Ctrl-4"},
    {commands::json_view::Level5, TKey('5', kbCtrlShift), "Ctrl-5"},
    {commands::json_view::Level6, TKey('6', kbCtrlShift), "Ctrl-6"},
    {commands::json_view::Level7, TKey('7', kbCtrlShift), "Ctrl-7"},
    {commands::json_view::Level8, TKey('8', kbCtrlShift), "Ctrl-8"},
    {commands::json_view::Level9, TKey('9', kbCtrlShift), "Ctrl-9"},

    {commands::chat::NewChat, TKey(kbCtrlN), "Ctrl-N"},
    {commands::chat::ManageModels, TKey(kbF2), "F2"},
    {commands::chat::ManagePrompts, TKey(kbF3), "F3"},
    {commands::chat::SendPrompt, TKey(kbCtrlEnter), "Ctrl-Enter"},

    {commands::edit::cmToggleWrap, TKey(kbCtrlW), "Ctrl-W"},
    {commands::edit::cmToggleMarkdownMode, TKey(kbCtrlM), "Ctrl-M"},
    {commands::edit::cmBold, TKey(kbCtrlB), "Ctrl-B"},
    {commands::edit::cmItalic, TKey(kbCtrlI), "Ctrl-I"},
    {commands::edit::cmBoldItalic, TKey('B', kbCtrlShift | kbShift), "Ctrl+Shift+B"},
    {commands::edit::cmStrikethrough, TKey('S', kbCtrlShift | kbShift), "Ctrl+Shift+S"},
    {commands::edit::cmInlineCode, TKey(kbCtrlK), "Ctrl-K"},
    {commands::edit::cmCodeBlock, TKey('K', kbCtrlShift | kbShift), "Ctrl+Shift+K"},
    {commands::edit::cmRemoveFormatting, TKey('0', kbCtrlShift | kbShift), "Ctrl+Shift+0"},
    {commands::edit::cmMakeParagraph, TKey('P', kbCtrlShift | kbShift), "Ctrl+Shift+P"},
    {commands::edit::cmToggleBlockQuote, TKey('Q', kbCtrlShift | kbShift), "Ctrl+Shift+Q"},
    {commands::edit::cmToggleBulletList, TKey('U', kbCtrlShift | kbShift), "Ctrl+Shift+U"},
    {commands::edit::cmToggleNumberedList, TKey('O', kbCtrlShift | kbShift), "Ctrl+Shift+O"},
    {commands::edit::cmConvertTaskList, TKey('T', kbCtrlShift | kbShift), "Ctrl+Shift+T"},
    {commands::edit::cmToggleTaskCheckbox, TKey('X', kbCtrlShift | kbShift), "Ctrl+Shift+X"},
    {commands::edit::cmIncreaseIndent, TKey(kbRight, kbCtrlShift | kbShift), "Ctrl+Shift+Right"},
    {commands::edit::cmDecreaseIndent, TKey(kbLeft, kbCtrlShift | kbShift), "Ctrl+Shift+Left"},
    {commands::edit::cmDefinitionList, TKey('D', kbCtrlShift | kbShift), "Ctrl+Shift+D"},
    {commands::edit::cmToggleSmartList, TKey('A', kbCtrlShift | kbShift), "Ctrl+Shift+A"},
    {commands::edit::cmInsertLink, TKey('L', kbCtrlShift | kbShift), "Ctrl+Shift+L"},
    {commands::edit::cmInsertReferenceLink, TKey('R', kbCtrlShift | kbShift), "Ctrl+Shift+R"},
    {commands::edit::cmAutoLinkSelection, TKey('Y', kbCtrlShift | kbShift), "Ctrl+Shift+Y"},
    {commands::edit::cmInsertImage, TKey('I', kbCtrlShift | kbShift), "Ctrl+Shift+I"},
    {commands::edit::cmInsertFootnote, TKey('N', kbCtrlShift | kbShift), "Ctrl+Shift+N"},
    {commands::edit::cmInsertHorizontalRule, TKey('H', kbCtrlShift | kbShift), "Ctrl+Shift+H"},
    {commands::edit::cmEscapeSelection, TKey('E', kbCtrlShift | kbShift), "Ctrl+Shift+E"},
    {commands::edit::cmInsertTable, TKey('T', kbCtrlShift | kbAltShift), "Ctrl+Alt+T"},
    {commands::edit::cmTableInsertRowAbove, TKey(kbUp, kbCtrlShift | kbAltShift), "Ctrl+Alt+Up"},
    {commands::edit::cmTableInsertRowBelow, TKey(kbDown, kbCtrlShift | kbAltShift), "Ctrl+Alt+Down"},
    {commands::edit::cmTableDeleteRow, TKey(kbDown, kbCtrlShift | kbAltShift | kbShift), "Ctrl+Alt+Shift+Down"},
    {commands::edit::cmTableInsertColumnBefore, TKey(kbLeft, kbCtrlShift | kbAltShift), "Ctrl+Alt+Left"},
    {commands::edit::cmTableInsertColumnAfter, TKey(kbRight, kbCtrlShift | kbAltShift), "Ctrl+Alt+Right"},
    {commands::edit::cmTableDeleteColumn, TKey(kbRight, kbCtrlShift | kbAltShift | kbShift), "Ctrl+Alt+Shift+Right"},
    {commands::edit::cmTableDeleteTable, TKey('T', kbCtrlShift | kbAltShift | kbShift), "Ctrl+Alt+Shift+T"},
    {commands::edit::cmTableAlignDefault, TKey('D', kbCtrlShift | kbAltShift), "Ctrl+Alt+D"},
    {commands::edit::cmTableAlignLeft, TKey('L', kbCtrlShift | kbAltShift), "Ctrl+Alt+L"},
    {commands::edit::cmTableAlignCenter, TKey('C', kbCtrlShift | kbAltShift), "Ctrl+Alt+C"},
    {commands::edit::cmTableAlignRight, TKey('R', kbCtrlShift | kbAltShift), "Ctrl+Alt+R"},
    {commands::edit::cmTableAlignNumber, TKey('N', kbCtrlShift | kbAltShift), "Ctrl+Alt+N"},
    {commands::edit::cmReflowParagraphs, TKey('P', kbCtrlShift | kbAltShift), "Ctrl+Alt+P"},
    {commands::edit::cmFormatDocument, TKey('F', kbCtrlShift | kbAltShift), "Ctrl+Alt+F"},
    {commands::edit::cmHeading1, TKey('1', kbCtrlShift | kbShift), "Ctrl+Shift+1"},
    {commands::edit::cmHeading2, TKey('2', kbCtrlShift | kbShift), "Ctrl+Shift+2"},
    {commands::edit::cmHeading3, TKey('3', kbCtrlShift | kbShift), "Ctrl+Shift+3"},
    {commands::edit::cmHeading4, TKey('4', kbCtrlShift | kbShift), "Ctrl+Shift+4"},
    {commands::edit::cmHeading5, TKey('5', kbCtrlShift | kbShift), "Ctrl+Shift+5"},
    {commands::edit::cmHeading6, TKey('6', kbCtrlShift | kbShift), "Ctrl+Shift+6"},
    {commands::edit::cmClearHeading, TKey('0', kbCtrlShift | kbShift), "Ctrl+Shift+0"},
    {commands::edit::cmInsertLineBreak, TKey(kbCtrlEnter), "Ctrl+Enter"},
};

const Scheme kBuiltInSchemes[] = {
    {"linux", "Linux", "Standard Turbo Vision shortcuts", std::span<const KeyBinding>(kLinuxBindings)},
    {"mac", "macOS", "Mac-friendly shortcuts without Alt combos", std::span<const KeyBinding>(kMacBindings)},
    {"windows", "Windows", "Windows-style shortcuts", std::span<const KeyBinding>(kLinuxBindings)},
    {"custom", "Custom", "User-defined overrides", std::span<const KeyBinding>()},
};

} // namespace

void registerBuiltinHotkeySchemes()
{
    registerCommandLabels(std::span<const CommandLabel>(kDefaultLabels));
    registerSchemes(std::span<const Scheme>(kBuiltInSchemes));
#if defined(__APPLE__)
    setActiveScheme("mac");
#else
    setActiveScheme("linux");
#endif
}

} // namespace ck::hotkeys
